"""update comment

Revision ID: 885f6eb68e2d
Revises: ade7563e383b
Create Date: 2020-09-01 16:16:53.122809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885f6eb68e2d'
down_revision = 'ade7563e383b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('path', sa.Text(), nullable=True))
    op.create_index(op.f('ix_comment_path'), 'comment', ['path'], unique=False)
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_path'), table_name='comment')
    op.drop_column('comment', 'path')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
